preset: symfony

risky: false

enabled:
    - single_quote
    - no_unused_imports
    - no_singleline_whitespace_before_semicolons
    - self_accessor
    - no_empty_statement
    - no_extra_consecutive_blank_lines
    - no_blank_lines_after_class_opening
    - include
    - no_trailing_comma_in_list_call
    - no_leading_namespace_whitespace
    binary_operator_spaces:
        -   default: align_single_space_minimal

finder:
    exclude:
        - "tests"
    name:
        - "*.php"
    path:
        - "src"
