language: php
php:
- '7.1'
- '7.2'
- '7.3'


before_install:
  - composer self-update
  - composer update -vv
script: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover