language: php
php:
- '7.1'
- '7.2'
- '7.3'


before_install:
  - composer self-update
  - composer update -vv
script: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
after_script:
  - if [ $(phpenv version-name) = "7.3" ]; then wget https://scrutinizer-ci.com/ocular.phar fi
  - if [ $(phpenv version-name) = "7.3" ]; then php ocular.phar code-coverage:upload  --access-token="f8ae6ce0df62b4b0b82cbf83b47429739567d4ba" --format=php-clover coverage.clover fi